import { useLiveQuery } from 'dexie-react-hooks';

import {
  db, getSettings, getCategories, getTransactions, getWishlistItems,
  getWishlistCategories, getIncomeEvents, getSubscriptions, getRules, getTemplates, getGoals,
} from '../db';

/**
 * Every live database read in the app, in one place.
 *
 * This is the *only* module besides `App.jsx` that reads from `db.js` — views
 * still receive data as props and emit mutations through callbacks. Keeping the
 * queries together makes the account-scoping rule (every table filtered by
 * `accountId`) checkable at a glance.
 *
 * The queries are written out one by one rather than generated by a helper:
 * `useLiveQuery` is a hook, so it cannot be called from inside a callback.
 */
export function useFinesseData(selectedAccountId) {
  // Left unscoped deliberately — this one drives the account switcher itself.
  // Stays `undefined` until the first read resolves, which is how App.jsx tells
  // "still loading" apart from "genuinely no accounts yet".
  const accountsQuery = useLiveQuery(() => db.accounts.toArray(), []);
  const accounts = accountsQuery || [];

  // Resolved here rather than corrected by an effect in App: if the selected
  // account has been deleted (or none is chosen yet) the first one stands in.
  // Doing it here keeps every scoped query below reading the *same* id that
  // App renders with — deriving it in App instead would leave the queries a
  // render behind, scoped to an account that no longer exists.
  const activeAccountId = accounts.some(account => Number(account.id) === Number(selectedAccountId))
    ? Number(selectedAccountId)
    : (accounts[0]?.id ?? null);
  const id = activeAccountId;
  const accountTransfers = useLiveQuery(() => db.accountTransfers.toArray(), []);

  const settings = useLiveQuery(() => (id ? getSettings(id) : null), [id]);
  const categories = useLiveQuery(() => (id ? getCategories(id) : []), [id]);
  const transactions = useLiveQuery(() => (id ? getTransactions(id) : []), [id]);
  const wishlistItems = useLiveQuery(() => (id ? getWishlistItems(id) : []), [id]);
  const wishlistCategories = useLiveQuery(() => (id ? getWishlistCategories(id) : []), [id]);
  const incomeEvents = useLiveQuery(() => (id ? getIncomeEvents(id) : []), [id]);
  const subscriptions = useLiveQuery(() => (id ? getSubscriptions(id) : []), [id]);
  const incomes = useLiveQuery(
    () => (id ? db.incomes.where('accountId').equals(id).toArray() : []), [id]);
  const variables = useLiveQuery(
    () => (id ? db.variables.where('accountId').equals(id).toArray() : []), [id]);
  const rules = useLiveQuery(() => (id ? getRules(id) : []), [id]);
  const templates = useLiveQuery(() => (id ? getTemplates(id) : []), [id]);
  const goals = useLiveQuery(() => (id ? getGoals(id) : []), [id]);

  return {
    accountsQuery,
    activeAccountId,
    accounts,
    accountTransfers: accountTransfers || [],
    settings,
    categories: categories || [],
    transactions: transactions || [],
    wishlistItems: wishlistItems || [],
    wishlistCategories: wishlistCategories || [],
    incomeEvents: incomeEvents || [],
    subscriptions: subscriptions || [],
    incomes: incomes || [],
    variables: variables || [],
    rules: rules || [],
    templates: templates || [],
    goals: goals || [],
  };
}
