import { useLiveQuery } from 'dexie-react-hooks';

import {
  db, getSettings, getCategories, getTransactions, getWishlistItems,
  getWishlistCategories, getIncomeEvents, getSubscriptions,
} from '../db';

/**
 * Every live database read in the app, in one place.
 *
 * This is the *only* module besides `App.jsx` that reads from `db.js` — views
 * still receive data as props and emit mutations through callbacks. Keeping the
 * queries together makes the account-scoping rule (every table filtered by
 * `accountId`) checkable at a glance.
 *
 * The queries are written out one by one rather than generated by a helper:
 * `useLiveQuery` is a hook, so it cannot be called from inside a callback.
 */
export function useFinesseData(activeAccountId) {
  const id = activeAccountId ? Number(activeAccountId) : null;

  // Left unscoped deliberately — this one drives the account switcher itself.
  // Stays `undefined` until the first read resolves, which is how App.jsx tells
  // "still loading" apart from "genuinely no accounts yet".
  const accountsQuery = useLiveQuery(() => db.accounts.toArray(), []);
  const accountTransfers = useLiveQuery(() => db.accountTransfers.toArray(), []);

  const settings = useLiveQuery(() => (id ? getSettings(id) : null), [id]);
  const categories = useLiveQuery(() => (id ? getCategories(id) : []), [id]);
  const transactions = useLiveQuery(() => (id ? getTransactions(id) : []), [id]);
  const wishlistItems = useLiveQuery(() => (id ? getWishlistItems(id) : []), [id]);
  const wishlistCategories = useLiveQuery(() => (id ? getWishlistCategories(id) : []), [id]);
  const incomeEvents = useLiveQuery(() => (id ? getIncomeEvents(id) : []), [id]);
  const subscriptions = useLiveQuery(() => (id ? getSubscriptions(id) : []), [id]);
  const incomes = useLiveQuery(
    () => (id ? db.incomes.where('accountId').equals(id).toArray() : []), [id]);
  const variables = useLiveQuery(
    () => (id ? db.variables.where('accountId').equals(id).toArray() : []), [id]);

  return {
    accountsQuery,
    accounts: accountsQuery || [],
    accountTransfers: accountTransfers || [],
    settings,
    categories: categories || [],
    transactions: transactions || [],
    wishlistItems: wishlistItems || [],
    wishlistCategories: wishlistCategories || [],
    incomeEvents: incomeEvents || [],
    subscriptions: subscriptions || [],
    incomes: incomes || [],
    variables: variables || [],
  };
}
