import { useLiveQuery } from 'dexie-react-hooks';

import {
  db, getSettings, getCategories, getTransactions, getWishlistItems,
  getWishlistCategories, getIncomeEvents, getSubscriptions, getRules, getTemplates, getGoals,
} from '../db';
import { buildNetWorthHistory } from '../utils';

/**
 * Every live database read in the app, in one place.
 *
 * This is the *only* module besides `App.jsx` that reads from `db.js` — views
 * still receive data as props and emit mutations through callbacks. Keeping the
 * queries together makes the account-scoping rule (every table filtered by
 * `accountId`) checkable at a glance — and, just as importantly, makes the
 * three deliberate exceptions to it obvious: `accounts`, `accountTransfers`
 * and `netWorth`, each of which is meaningless scoped to a single account.
 *
 * The queries are written out one by one rather than generated by a helper:
 * `useLiveQuery` is a hook, so it cannot be called from inside a callback.
 *
 * `vault` is the fourth deliberate exception to the account-scoping rule, and
 * the only table the encryption middleware leaves in the clear — it holds the
 * wrapped key, so it cannot be encrypted with it. It is read here rather than
 * in App so that every live query still lives in one file, and because the
 * gate it drives has to be decided before any other query runs: on an encrypted
 * device every row is unreadable until the key is unwrapped, and a query that
 * jumped the gun would throw rather than return nothing. Until the vault is
 * either absent or unlocked, each query below short-circuits to the same empty
 * value it uses before an account is chosen.
 *
 * `lock` is the fifth, and exists for the same reason one step earlier: the
 * screen lock has to be decided before the first paint, not after `settings`
 * arrives. See its own comment below.
 */
export function useFinesseData(selectedAccountId, unlocked = true) {
  // `undefined` while the read is in flight, which is what stops the app
  // deciding "not encrypted" during the first frame and querying through it.
  const vault = useLiveQuery(() => db.vault.toArray().then(rows => rows[0] || null), []);
  const encryptionEnabled = Boolean(vault);
  const ready = vault !== undefined && (!encryptionEnabled || unlocked);

  /**
   * Whether a lock stands between the launch and the app — answered here,
   * before anything is rendered, and independently of `settings` below.
   *
   * It cannot be derived from that query: it is scoped to an account, so until
   * `accounts` resolves it short-circuits to `null`, which reads exactly like
   * "no PIN set". The app would paint a dashboard on the first frame and swap
   * the lock screen in once settings arrived — which is the one thing a lock
   * must never do. Staying `undefined` until the answer is known is what lets
   * App hold the whole tree back instead.
   *
   * A vault answers on its own, and is checked first: sealed rows can't be read
   * without the key, so the settings table is only consulted when there is no
   * vault — the only case in which it is readable anyway.
   *
   * Unscoped deliberately, and a fifth exception to the account-scoping rule: a
   * PIN covers the device, not one account, so a PIN set against any account
   * locks the app. The row that carries it comes back with the answer, because
   * that is the row the entered PIN has to be verified against — the active
   * account is not necessarily the one it was set on.
   */
  const lock = useLiveQuery(async () => {
    if (vault === undefined) return undefined;
    if (vault) return { required: true, pinSettings: null };
    const rows = await db.settings.toArray();
    const withPin = rows.find(row => row.pinHash && row.pinSalt) || null;
    return { required: Boolean(withPin), pinSettings: withPin };
  }, [vault]);

  // Left unscoped deliberately — this one drives the account switcher itself.
  // Stays `undefined` until the first read resolves, which is how App.jsx tells
  // "still loading" apart from "genuinely no accounts yet".
  const accountsQuery = useLiveQuery(() => (ready ? db.accounts.toArray() : undefined), [ready]);
  const accounts = accountsQuery || [];

  // Resolved here rather than corrected by an effect in App: if the selected
  // account has been deleted (or none is chosen yet) the first one stands in.
  // Doing it here keeps every scoped query below reading the *same* id that
  // App renders with — deriving it in App instead would leave the queries a
  // render behind, scoped to an account that no longer exists.
  const activeAccountId = accounts.some(account => Number(account.id) === Number(selectedAccountId))
    ? Number(selectedAccountId)
    : (accounts[0]?.id ?? null);
  const id = activeAccountId;
  const accountTransfers = useLiveQuery(
    () => (ready ? db.accountTransfers.toArray() : []), [ready]);

  const settings = useLiveQuery(() => (ready && id ? getSettings(id) : null), [id, ready]);
  const categories = useLiveQuery(() => (ready && id ? getCategories(id) : []), [id, ready]);
  const transactions = useLiveQuery(() => (ready && id ? getTransactions(id) : []), [id, ready]);
  const wishlistItems = useLiveQuery(() => (ready && id ? getWishlistItems(id) : []), [id, ready]);
  const wishlistCategories = useLiveQuery(() => (ready && id ? getWishlistCategories(id) : []), [id, ready]);
  const incomeEvents = useLiveQuery(() => (ready && id ? getIncomeEvents(id) : []), [id, ready]);
  const subscriptions = useLiveQuery(() => (ready && id ? getSubscriptions(id) : []), [id, ready]);
  const incomes = useLiveQuery(
    () => (ready && id ? db.incomes.where('accountId').equals(id).toArray() : []), [id, ready]);
  const variables = useLiveQuery(
    () => (ready && id ? db.variables.where('accountId').equals(id).toArray() : []), [id, ready]);
  const rules = useLiveQuery(() => (ready && id ? getRules(id) : []), [id, ready]);
  const templates = useLiveQuery(() => (ready && id ? getTemplates(id) : []), [id, ready]);
  const goals = useLiveQuery(() => (ready && id ? getGoals(id) : []), [id, ready]);

  // Net worth is cross-account by definition — "everything I own, minus
  // everything I owe" stops meaning anything if it only counts one account. So
  // this is the third deliberate exception to the scoping rule, after
  // `accounts` and `accountTransfers`.
  //
  // It returns the computed summary rather than the raw rows, which keeps
  // unscoped transactions and goals from leaking into props where a scoped
  // view might use them by mistake — the exception stays contained to the one
  // figure that needs it. `buildNetWorthHistory` is pure, so running it here
  // costs only the work the query already implies.
  const netWorth = useLiveQuery(async () => {
    if (!ready) return null;
    const [accountRows, txs, events, transferRows, goalRows] = await Promise.all([
      db.accounts.toArray(),
      db.transactions.toArray(),
      db.incomeEvents.toArray(),
      db.accountTransfers.toArray(),
      db.goals.toArray(),
    ]);
    return buildNetWorthHistory({
      accounts: accountRows,
      transactions: txs,
      incomeEvents: events,
      transfers: transferRows,
      goals: goalRows,
      days: 90,
    });
  }, [ready]);

  return {
    vault: vault || null,
    lock: lock || null,
    lockChecked: lock !== undefined,
    encryptionEnabled,
    ready,
    netWorth: netWorth || null,
    accountsQuery,
    activeAccountId,
    accounts,
    accountTransfers: accountTransfers || [],
    settings,
    categories: categories || [],
    transactions: transactions || [],
    wishlistItems: wishlistItems || [],
    wishlistCategories: wishlistCategories || [],
    incomeEvents: incomeEvents || [],
    subscriptions: subscriptions || [],
    incomes: incomes || [],
    variables: variables || [],
    rules: rules || [],
    templates: templates || [],
    goals: goals || [],
  };
}
